#!/bin/bash

SUM=0   # sum of scores
NUM=0   # number of scores

while true; do
  echo -n "Enter your score ('q' for quit): "; read SCORE
  if [[ $SCORE == "q" ]]; then
     break
  fi
  if (($SCORE < 0 || $SCORE > 100)); then
     echo "Invalid score, please re-enter: "
  else
     SUM=$((SUM + SCORE)); NUM=$((NUM + 1))
  fi
done
echo Average rating: $((SUM/NUM))%
